import type { RestaurantConfig } from '@/types/restaurant'

export const gangnamKitchenConfig: RestaurantConfig = {
  slug: 'gangnam-kitchen',

  identity: {
    name: 'Gangnam Kitchen',
    koreanName: '강남 키친',
    tagline: 'Seoul Flavours, Crafted in Pune.',
    description: "Pune's most premium Korean dining experience.",
    established: '2019',
    rating: '4.9',
    reviewCount: '200+',
    menuCount: '50+',
    guestCount: '200+',
  },

  location: {
    address: 'Lane 7, Koregaon Park',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411001',
    country: 'India',
    neighborhood: 'Koregaon Park',
    mapEmbedUrl:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.4278!2d73.8929!3d18.5363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2c1471de2ef95%3A0xdc4abf5b21a41a37!2sKoregaon%20Park%2C%20Pune%2C%20Maharashtra!5e0!3m2!1sen!2sin!4v1620000000000!5m2!1sen!2sin',
    googleMapsUrl: 'https://maps.google.com/?q=Koregaon+Park+Pune',
  },

  contact: {
    phone: '+91 98765 43210',
    email: 'hello@gangnamkitchen.in',
    instagram: '@gangnamkitchenpune',
    instagramUrl: 'https://instagram.com/gangnamkitchenpune',
  },

  hours: [
    { days: 'Mon – Fri', time: '12pm – 10pm' },
    { days: 'Sat – Sun', time: '11am – 11pm' },
  ],

  hero: {
    line1: 'Seoul',
    line2: 'Flavours,',
    line3: 'Crafted in',
    accentWord: 'Pune.',
    subtext:
      'An intimate Korean dining experience where each dish carries the spirit of Seoul — brought to life in the heart of Pune.',
    locationTag: 'Koregaon Park · Pune · India',
  },

  images: {
    hero: '',
    heroFallback: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1920&q=85',
    restaurant: '',
    restaurantFallback: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=85',
    chef: '',
    chefFallback: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=800&q=85',
    interior: '',
    interiorFallback: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=85',
    reservationCta: '',
    reservationCtaFallback:
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&q=85',
  },

  // ── Featured dishes (homepage DishesSection — 8 items) ──────────────────
  dishes: [
    {
      id: 'korean-fried-chicken',
      name: 'Korean Fried Chicken',
      koreanName: '치킨',
      description:
        'Double-fried to shattering crispness, glazed in our house gochujang sauce. A textural revelation.',
      price: 520,
      category: 'mains',
      tags: ['Bestseller', 'Spicy'],
      spice: 2,
      imageKey: 'korean-fried-chicken',
      featured: true,
      size: 'large',
    },
    {
      id: 'bibimbap',
      name: 'Bibimbap',
      koreanName: '비빔밥',
      description:
        'Stone-bowl rice crowned with seasonal vegetables, a soft egg, and house-made gochujang.',
      price: 440,
      category: 'mains',
      tags: ['Vegetarian Option'],
      spice: 1,
      imageKey: 'bibimbap',
      size: 'small',
    },
    {
      id: 'tteokbokki',
      name: 'Tteokbokki',
      koreanName: '떡볶이',
      description:
        'Silken rice cakes simmered in a spiced scarlet broth — Seoul street food, perfected.',
      price: 360,
      category: 'street',
      tags: ['Vegan'],
      spice: 3,
      imageKey: 'tteokbokki',
      size: 'small',
    },
    {
      id: 'korean-bbq',
      name: 'Korean BBQ',
      koreanName: '바베큐',
      description:
        'Premium cuts marinated overnight in soy, sesame and Korean pear. Grilled tableside.',
      price: 980,
      category: 'bbq',
      tags: ['Signature', 'For Two'],
      spice: 0,
      imageKey: 'korean-bbq',
      featured: true,
      size: 'wide',
    },
    {
      id: 'ramen',
      name: 'Korean Ramen',
      koreanName: '라면',
      description:
        'Slow-simmered pork bone broth, silky noodles, a marinated egg, and house kimchi.',
      price: 480,
      category: 'noodles',
      tags: ['Comfort'],
      spice: 1,
      imageKey: 'ramen',
      size: 'small',
    },
    {
      id: 'kimchi-rice',
      name: 'Kimchi Fried Rice',
      koreanName: '김치볶음밥',
      description:
        'Three-day fermented kimchi wok-fried into butter rice, topped with a crispy egg.',
      price: 380,
      category: 'noodles',
      tags: ['Vegetarian'],
      spice: 2,
      imageKey: 'kimchi-rice',
      size: 'small',
    },
    {
      id: 'korean-corn-dog',
      name: 'Korean Corn Dog',
      koreanName: '핫도그',
      description:
        'Mozzarella-stuffed, panko-rolled, drizzled in sugar and sauce. Seoul in one bite.',
      price: 280,
      category: 'street',
      tags: ['Street Food'],
      spice: 0,
      imageKey: 'korean-corn-dog',
      size: 'small',
    },
    {
      id: 'bingsu',
      name: 'Bingsu',
      koreanName: '빙수',
      description:
        'Shaved milk ice dusted with house red bean paste, condensed milk, and seasonal toppings.',
      price: 320,
      category: 'desserts',
      tags: ['Dessert'],
      spice: 0,
      imageKey: 'bingsu',
      size: 'small',
    },
  ],

  // ── Full menu (Menu page — 17 items) ────────────────────────────────────
  menuItems: [
    {
      id: 'bibimbap',
      name: 'Bibimbap',
      koreanName: '비빔밥',
      description:
        'Stone-pot rice with six seasonal vegetables, a slow-cooked egg, sesame oil, and our house-made gochujang paste. Mixed tableside.',
      price: 440,
      category: 'mains',
      tags: ['Vegetarian'],
      spice: 1,
      imageKey: 'bibimbap',
      featured: true,
    },
    {
      id: 'dolsot-bibimbap',
      name: 'Dolsot Bibimbap',
      koreanName: '돌솥비빔밥',
      description:
        'Our signature bibimbap served in a scorching stone bowl — the bottom layer of rice crisps to perfection. Topped with grilled chicken.',
      price: 520,
      category: 'mains',
      tags: [],
      spice: 1,
      imageKey: 'bibimbap',
      featured: false,
    },
    {
      id: 'sundubu-jjigae',
      name: 'Sundubu Jjigae',
      koreanName: '순두부찌개',
      description:
        'Silken tofu stew simmered in a fiery red broth with mushrooms, zucchini, and a cracked egg. Classic Korean comfort in a clay pot.',
      price: 420,
      category: 'mains',
      tags: ['Vegetarian', 'Spicy'],
      spice: 3,
      imageKey: 'tteokbokki',
      featured: false,
    },
    {
      id: 'korean-fried-chicken',
      name: 'Korean Fried Chicken',
      koreanName: '양념치킨',
      description:
        'Double-fried for maximum crunch. Half glazed in gochujang-honey sauce, half in soy-garlic. Served with pickled radish.',
      price: 520,
      category: 'mains',
      tags: ['Bestseller'],
      spice: 2,
      imageKey: 'korean-fried-chicken',
      featured: true,
    },
    {
      id: 'samgyeopsal',
      name: 'Samgyeopsal',
      koreanName: '삼겹살',
      description:
        'Thick-cut pork belly marinated overnight in a blend of Korean pear, soy, and sesame. Grilled tableside over live charcoal. For two.',
      price: 980,
      category: 'bbq',
      tags: ['For Two', 'Signature'],
      spice: 0,
      imageKey: 'korean-bbq',
      featured: true,
    },
    {
      id: 'bulgogi',
      name: 'Bulgogi',
      koreanName: '불고기',
      description:
        'Paper-thin beef sirloin marinated in soy, Asian pear, garlic, and ginger. Wok-kissed to caramelised perfection. With steamed rice.',
      price: 860,
      category: 'bbq',
      tags: ['Premium'],
      spice: 0,
      imageKey: 'korean-bbq',
      featured: false,
    },
    {
      id: 'dak-galbi',
      name: 'Dak Galbi',
      koreanName: '닭갈비',
      description:
        'Spicy stir-fried chicken with rice cakes, cabbage, and sweet potato in a rich gochujang glaze. A Chuncheon classic.',
      price: 680,
      category: 'bbq',
      tags: ['Spicy'],
      spice: 3,
      imageKey: 'korean-bbq',
      featured: false,
    },
    {
      id: 'ramen',
      name: 'Tonkotsu Ramen',
      koreanName: '라면',
      description:
        'Eighteen-hour pork bone broth, springy ramen noodles, a 63°C marinated egg, chashu, bamboo shoots, and house kimchi.',
      price: 480,
      category: 'noodles',
      tags: ['Comfort'],
      spice: 1,
      imageKey: 'ramen',
      featured: true,
    },
    {
      id: 'kimchi-rice',
      name: 'Kimchi Bokkeumbap',
      koreanName: '김치볶음밥',
      description:
        '72-hour fermented kimchi wok-fried in sesame butter with rice, scallions, and a runny fried egg.',
      price: 380,
      category: 'noodles',
      tags: ['Vegetarian'],
      spice: 2,
      imageKey: 'kimchi-rice',
      featured: false,
    },
    {
      id: 'jajangmyeon',
      name: 'Jajangmyeon',
      koreanName: '자장면',
      description:
        "Thick wheat noodles in a rich black bean sauce with pork, onion, and zucchini. Korea's most beloved comfort noodle.",
      price: 420,
      category: 'noodles',
      tags: [],
      spice: 0,
      imageKey: 'ramen',
      featured: false,
    },
    {
      id: 'tteokbokki',
      name: 'Tteokbokki',
      koreanName: '떡볶이',
      description:
        "Silken rice cakes in a scarlet gochujang broth with fish cakes, scallions, and a soft-boiled egg. Seoul's most iconic street bite.",
      price: 360,
      category: 'street',
      tags: ['Vegan', 'Spicy'],
      spice: 3,
      imageKey: 'tteokbokki',
      featured: true,
    },
    {
      id: 'korean-corn-dog',
      name: 'Mozzarella Corn Dog',
      koreanName: '모짜렐라 핫도그',
      description:
        'Stretchy mozzarella wrapped in a panko-rice flour batter, deep-fried to golden. Dusted with sugar, drizzled with mustard and ketchup.',
      price: 280,
      category: 'street',
      tags: ['Vegetarian'],
      spice: 0,
      imageKey: 'korean-corn-dog',
      featured: false,
    },
    {
      id: 'pajeon',
      name: 'Haemul Pajeon',
      koreanName: '해물파전',
      description:
        'A crispy Korean seafood pancake loaded with prawns, squid, and spring onions. Served with a house soy-sesame dipping sauce.',
      price: 420,
      category: 'street',
      tags: [],
      spice: 0,
      imageKey: 'korean-fried-chicken',
      featured: false,
    },
    {
      id: 'bingsu',
      name: 'Patbingsu',
      koreanName: '팥빙수',
      description:
        'Fine-shaved milk ice, house-made sweet red bean paste, condensed milk, mochi bites, and seasonal fresh fruit.',
      price: 320,
      category: 'desserts',
      tags: ['Vegetarian'],
      spice: 0,
      imageKey: 'bingsu',
      featured: true,
    },
    {
      id: 'hotteok',
      name: 'Hotteok',
      koreanName: '호떡',
      description:
        'Crispy pan-fried sweet pancakes filled with brown sugar, cinnamon, and crushed walnuts. A Seoul street winter classic.',
      price: 240,
      category: 'desserts',
      tags: ['Vegetarian'],
      spice: 0,
      imageKey: 'bingsu',
      featured: false,
    },
    {
      id: 'sikhye',
      name: 'Sikhye',
      koreanName: '식혜',
      description:
        'Traditional Korean sweet rice punch. Gently fermented, lightly chilled, and subtly fragrant with ginger. Non-alcoholic.',
      price: 180,
      category: 'drinks',
      tags: ['Non-Alcoholic', 'Vegetarian'],
      spice: 0,
      imageKey: 'bingsu',
      featured: false,
    },
    {
      id: 'soju-cocktail',
      name: 'Yuzu Soju Splash',
      koreanName: '유자 소주',
      description:
        'House soju mixed with fresh yuzu juice, sparkling water, and a rim of Tajin salt. Light, citrusy, dangerously easy to drink.',
      price: 380,
      category: 'drinks',
      tags: ['Alcoholic'],
      spice: 0,
      imageKey: 'bingsu',
      featured: true,
    },
  ],

  // ── Testimonials ────────────────────────────────────────────────────────
  testimonials: [
    {
      id: '1',
      name: 'Ananya Sharma',
      location: 'Koregaon Park, Pune',
      rating: 5,
      text: "Gangnam Kitchen is the closest I've felt to actually being in Seoul — without leaving Pune. The Bibimbap was revelatory, and the interiors are something out of a magazine. I've already been three times this month.",
      occasion: 'Date Night',
      initial: 'A',
    },
    {
      id: '2',
      name: 'Rohan Mehta',
      location: 'Baner, Pune',
      rating: 5,
      text: 'The Korean BBQ here is the real deal. The marinade on the pork belly is extraordinary — you can taste the difference that proper Korean pantry ingredients make. The tableside grilling experience is intimate and memorable.',
      occasion: 'Family Dinner',
      initial: 'R',
    },
    {
      id: '3',
      name: 'Priya Nair',
      location: 'Kalyani Nagar, Pune',
      rating: 5,
      text: 'I came for the Tteokbokki and stayed for everything else. The space feels like a Hongdae café transported to Pune — warm lighting, subtle K-pop in the background, and food that makes you close your eyes mid-bite.',
      occasion: 'Girls\' Brunch',
      initial: 'P',
    },
    {
      id: '4',
      name: 'Vikram Iyer',
      location: 'Viman Nagar, Pune',
      rating: 5,
      text: 'As someone who lived in Seoul for two years, I was skeptical. Then I had the Ramen. The broth is the kind that takes all day — rich, layered, deeply comforting. They\'re not cutting corners here.',
      occasion: 'Solo Dining',
      initial: 'V',
    },
    {
      id: '5',
      name: 'Meera Kulkarni',
      location: 'Aundh, Pune',
      rating: 5,
      text: 'The Bingsu alone is worth the trip. Every element of the meal felt considered — from the hand-folded dumplings to the perfectly fermented kimchi. Gangnam Kitchen doesn\'t cut corners, and it absolutely shows.',
      occasion: 'Birthday Celebration',
      initial: 'M',
    },
    {
      id: '6',
      name: 'Kabir Singhania',
      location: 'Camp, Pune',
      rating: 5,
      text: "Most Korean restaurants in India play it safe. Gangnam Kitchen doesn't. The gochujang levels are authentic, the portions are generous, and the service is attentive without being intrusive.",
      occasion: 'Corporate Lunch',
      initial: 'K',
    },
  ],

  // ── Gallery ─────────────────────────────────────────────────────────────
  gallery: [
    { id: 'g1', local: '', fallback: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80', alt: 'Korean BBQ experience', category: 'food', aspect: 'portrait' },
    { id: 'g2', local: '', fallback: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80', alt: 'Ramen close-up', category: 'food', aspect: 'landscape' },
    { id: 'g3', local: '', fallback: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80', alt: 'Restaurant ambience', category: 'ambience', aspect: 'portrait' },
    { id: 'g4', local: '', fallback: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80', alt: 'Bibimbap artful plating', category: 'food', aspect: 'square' },
    { id: 'g5', local: '', fallback: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&q=80', alt: 'Korean café vibe', category: 'ambience', aspect: 'landscape' },
    { id: 'g6', local: '', fallback: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80', alt: 'Premium food styling', category: 'food', aspect: 'portrait' },
    { id: 'g7', local: '', fallback: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80', alt: 'Restaurant interior', category: 'ambience', aspect: 'landscape' },
    { id: 'g8', local: '', fallback: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80', alt: 'Korean dessert bingsu', category: 'food', aspect: 'square' },
    { id: 'g9', local: '', fallback: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80', alt: 'Korean table setting', category: 'ambience', aspect: 'square' },
    { id: 'g10', local: '', fallback: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80', alt: 'Tteokbokki close-up', category: 'food', aspect: 'portrait' },
    { id: 'g11', local: '', fallback: 'https://images.unsplash.com/photo-1602273660127-a0000560a47c?w=800&q=80', alt: 'Korean fried chicken plating', category: 'food', aspect: 'landscape' },
    { id: 'g12', local: '', fallback: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800&q=80', alt: 'Weekend brunch spread', category: 'food', aspect: 'landscape' },
  ],
}